sudo: required
dist: bionic

os: linux
language: minimal

services:
  - docker

cache:
  ccache: true
  directories:
    - $HOME/cache

stages:
  - build depends
  - build src

builddepends: &builddepends
  stage: build depends
  script:
    - $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh

buildsrc: &buildsrc
  stage: build src
  script:
    - $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh
    - $DOCKER_RUN_IN_BUILDER ./ci/build_src.sh

jobs:
  include:
    # build depends
    - <<: *builddepends
      env: BUILD_TARGET=win64
    #- <<: *builddepends
      #env: BUILD_TARGET=linux64
    # build source
    - <<: *buildsrc
      #env: BUILD_TARGET=win64
    #- <<: *buildsrc
      #env: BUILD_TARGET=linux64
      
before_cache:
  # Save builder image
  - docker save travis-builder-$BUILD_TARGET-$TRAVIS_JOB_NUMBER $(docker history -q travis-builder-$BUILD_TARGET-$TRAVIS_JOB_NUMBER | grep -v \<missing\>) | gzip -2 > $HOME/cache/docker/travis-builder-$BUILD_TARGET.tar.gz

install:
    # Fix annoying Travis bug: a branch with a single commit has an empty TRAVIS_COMMIT_RANGE sometimes
    - if [ -z "$TRAVIS_COMMIT_RANGE" ]; then export TRAVIS_COMMIT_RANGE="HEAD~..HEAD"; fi
    # Our scripts try to be Travis agnostic
    - export PULL_REQUEST="$TRAVIS_PULL_REQUEST"
    - export COMMIT_RANGE="$TRAVIS_COMMIT_RANGE"
    - export JOB_NUMBER="$TRAVIS_JOB_NUMBER"
    - export HOST_SRC_DIR=$TRAVIS_BUILD_DIR
    - export HOST_CACHE_DIR=$HOME/cache
    - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
    - source ./ci/matrix.sh
    - mkdir -p $HOST_CACHE_DIR/docker && mkdir -p $HOST_CACHE_DIR/ccache && mkdir -p $HOST_CACHE_DIR/depends && mkdir -p $HOST_CACHE_DIR/sdk-sources
    # Keep this as it makes caching related debugging easier
    - ls -lah $HOST_CACHE_DIR && ls -lah $HOST_CACHE_DIR/depends && ls -lah $HOST_CACHE_DIR/ccache && ls -lah $HOST_CACHE_DIR/docker
    # Load cached builder image
    - if [ -f $HOST_CACHE_DIR/docker/travis-builder-$BUILD_TARGET.tar.gz ]; then zcat $HOST_CACHE_DIR/docker/travis-builder-$BUILD_TARGET.tar.gz | docker load || true; fi
    - travis_retry docker pull ubuntu:bionic
    - travis_retry docker build -t $BUILDER_IMAGE_NAME --build-arg=USER_ID=$UID --build-arg=GROUP_ID=$UID --build-arg=BUILD_TARGET=$BUILD_TARGET -f ci/Dockerfile.builder ci
before_script:
    # Make sure stdout is in blocking mode. Otherwise builds will fail due to large writes to stdout
    # See https://github.com/travis-ci/travis-ci/issues/4704. If this gets fixed, this line can also be removed.
    - python3 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
    - echo $TRAVIS_COMMIT_RANGE
    - echo $TRAVIS_COMMIT_LOG
before_deploy:
  - sudo chown -R travis:travis /home/travis/
  - "cd ./ci/"
  - "chmod +x deploy.sh"
  - "./deploy.sh"
deploy:
  provider: releases
  api_key:
    secure: "2F9XZsgs7mF/Ry1zulqfgelXV77N+Tt1Uno94jL85VybMfUNSEVeXG1rOWU2IiTFRNpIRZ728gF0PLyikefqqYA8A+0fyiEIbr70IRmBtK9WoVKAnaSb4IY2BYpBkJVj44XKno2cfUMTUFp3RJB9R9Fp/eZIPKzFekC4nmpxnCneLuk8jtC9GrrbU6kqSA3hhqBtx+40dM3zR9nDOq30CvBhqDHK5n/Ux3ddbi0JKgELZDOOzfdZi82mHEs86FX/Ai77bEzF6Cp13HUIQ9IkbJ/b9vgEZHpoaCNDejUUiumoGbJhWD97OQD47PJXHxZhlGOvW5hROWPXKjarxh0tgD24+KEDpTVUqvq0GToVf3Bpv93JEL+PYjjCEJ9iGxJR130m0PYtgIl+M8gPHfP/J+qRDUieyYkrNI0mN6FGe3hgmumsqMnCcIAA7rQRDkYUxBJzAOChqSPbrV62omhsIsVATLzC3ExPulZXKPmKLn10+7INPE5itx2NvjgnpKlgoZwo4FjxEAHuLF/PPOyAfEpQ6wkx7IBE7BCOOuNs2aVhXjiq75v2WIcNaeOgOI5uwtDE8T21C47N0cbybjfuWuj9z6gJu4LZ2MsRlhuRGlDV0GnI/0r89dsoUH06v3JtRztYBiikcbIKJytjaJiAGY0dcPh7RNXT6d3S6Xj68Wk="
  file_glob: true
  file:
    - out/**/zip/*
    - /home/travis/build/404tests/firo/build-ci/firo-$BUILD_TARGET/src/bin/zip/*
  skip_cleanup: true
  on:
    tags: true
