sudo: required
dist: bionic

os: linux
language: minimal

services:
  - docker

cache:
  ccache: true
  directories:
    - $HOME/cache

stages:
  - build depends
  - build src

builddepends: &builddepends
  stage: build depends
  script:
    - $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh

buildsrc: &buildsrc
  stage: build src
  script:
    - $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh
    - $DOCKER_RUN_IN_BUILDER ./ci/build_src.sh

jobs:
  include:
    # build depends
    - <<: *builddepends
      env: BUILD_TARGET=win64
    #- <<: *builddepends
      #env: BUILD_TARGET=linux64
    # build source
    - <<: *buildsrc
      env: BUILD_TARGET=win64
    #- <<: *buildsrc
      #env: BUILD_TARGET=linux64
      
before_cache:
  # Save builder image
  - docker save travis-builder-$BUILD_TARGET-$TRAVIS_JOB_NUMBER $(docker history -q travis-builder-$BUILD_TARGET-$TRAVIS_JOB_NUMBER | grep -v \<missing\>) | gzip -2 > $HOME/cache/docker/travis-builder-$BUILD_TARGET.tar.gz

install:
    # Fix annoying Travis bug: a branch with a single commit has an empty TRAVIS_COMMIT_RANGE sometimes
    - if [ -z "$TRAVIS_COMMIT_RANGE" ]; then export TRAVIS_COMMIT_RANGE="HEAD~..HEAD"; fi
    # Our scripts try to be Travis agnostic
    - export PULL_REQUEST="$TRAVIS_PULL_REQUEST"
    - export COMMIT_RANGE="$TRAVIS_COMMIT_RANGE"
    - export JOB_NUMBER="$TRAVIS_JOB_NUMBER"
    - export HOST_SRC_DIR=$TRAVIS_BUILD_DIR
    - export HOST_CACHE_DIR=$HOME/cache
    - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
    - source ./ci/matrix.sh
    - mkdir -p $HOST_CACHE_DIR/docker && mkdir -p $HOST_CACHE_DIR/ccache && mkdir -p $HOST_CACHE_DIR/depends && mkdir -p $HOST_CACHE_DIR/sdk-sources
    # Keep this as it makes caching related debugging easier
    - ls -lah $HOST_CACHE_DIR && ls -lah $HOST_CACHE_DIR/depends && ls -lah $HOST_CACHE_DIR/ccache && ls -lah $HOST_CACHE_DIR/docker
    # Load cached builder image
    - if [ -f $HOST_CACHE_DIR/docker/travis-builder-$BUILD_TARGET.tar.gz ]; then zcat $HOST_CACHE_DIR/docker/travis-builder-$BUILD_TARGET.tar.gz | docker load || true; fi
    - travis_retry docker pull ubuntu:bionic
    - travis_retry docker build -t $BUILDER_IMAGE_NAME --build-arg=USER_ID=$UID --build-arg=GROUP_ID=$UID --build-arg=BUILD_TARGET=$BUILD_TARGET -f ci/Dockerfile.builder ci
before_script:
    # Make sure stdout is in blocking mode. Otherwise builds will fail due to large writes to stdout
    # See https://github.com/travis-ci/travis-ci/issues/4704. If this gets fixed, this line can also be removed.
    - python3 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
    - echo $TRAVIS_COMMIT_RANGE
    - echo $TRAVIS_COMMIT_LOG
before_deploy:
  - sudo chown -R travis:travis /home/travis/
  - "cd ./ci/"
  - "chmod +x deploy.sh"
  - "./deploy.sh"
deploy:
  provider: releases
  api_key:
    secure: "bYOqRlfEgtjils4fgDJk/62Gi4TP/LjVauMb1PbZA3zzDkJs0Kki+2nKvL8+DPTttppebp1n64I8ANDEGgBpskq1MFOJpCCMIkCyqtUEF3QXV29ySXfveIjfEwms2tIDOj6AW4UXv3j8CciLf0fErFrAI0/MpOyqHi9V563iB4Yt/nQC8oSW0PXU8cG3RIQNEef9hdSugT22ejidFqbNDTfgPohkejD0Qa7Hb99GPX5k6LS/FQGtEAMRIcqupVeye2Y2bMmz8e7cT8JB4WJW5H5MBBX6UJwtnFpCZUJX+0IdbxBekYzFkGJMO2xMdOuKaHjU0If+F04wY9T8bplWS9ptCGexS00Yvx4ZQrOq1/70wqrorgC549bLLlunoKEz3t0Lh/KZbNR4ErcFnSZkPVNKmhShhDINuP21AD1Avl7kHGozRyCjn3PpVVDbxHGSneUrja75mGa9nmojwqY4HtC+lkXRrlHrg0gq/m5OfqVp+6HiXpcWkZeKWYMTjJ2U3+3mtAOZ1zd+w0z54f2sekocDXWph0uTmtEXwI9X3FsT8UeeRp31WhhISLY1DGpeI8plT616SQl4E//W8937Sluysw+xl9hm+QyVrIuxJCejjkHMg3KPk2L825ZgP/5HAib9dYk/9zsY4v++vVdpxpB5ooP2czSqn2i7tof4yzQ="
  file_glob: true
  file:
    - out/**/zip/*
    - /home/travis/build/707tests/BZX/build-ci/BZX-$BUILD_TARGET/src/bin/zip/*
  skip_cleanup: true
  on:
    tags: true
